# Generated by Django 5.0.2 on 2024-02-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Circuit',
        ),
    ]
