# Generated by Django 5.0.2 on 2024-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0003_rename_circuitname_circuit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='image',
            field=models.FileField(null=True, upload_to='media/static/img'),
        ),
    ]
