# Generated by Django 5.0.2 on 2024-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0004_alter_circuit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='gif',
            field=models.ImageField(null=True, upload_to='media/static/gif'),
        ),
    ]
