# Generated by Django 5.0.2 on 2024-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0006_alter_circuit_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='gif',
            field=models.FileField(null=True, upload_to='circuit'),
        ),
    ]
