# Generated by Django 5.0.2 on 2024-02-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0007_alter_circuit_gif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='gif',
            new_name='gifs',
        ),
    ]
