# Generated by Django 5.0.2 on 2024-02-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0008_rename_gif_circuit_gifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='gifs',
        ),
        migrations.AddField(
            model_name='circuit',
            name='gif',
            field=models.FileField(null=True, upload_to='media/static/gif'),
        ),
    ]
